#!/bin/bash
# Linux/UNIX box with ssh key based login enabled
# SSH User name

# this will be the dumbest code I ever do.
# Need to fix the seg faulted TFractionFitter results.
# I know which file numbers didn't work. So I will hand code them now to work.

x=147
rm histfitter.cc
sed 's/ReplaceWithIndexLow/'$x'/g' master_histfitter.cc > histfitter.cc
sed -i 's/ReplaceWithIndexHigh/'$((x+1))'/g' histfitter.cc
make
./histfitter
make clean

rm histfitter.cc
